// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Navigation": {
        "home": "Home",
        "projects": "Projects",
        "experience": "Experience",
        "about-me": "About Me",
        "blog": "Blog",
        "contact": "Contact"
    },
    "LocaleSwitcher": {
        "label": "Change Language",
        "locale": "{locale, select, es {es Spanish} en {🇺🇸 English}}"
    },
    "Metadata": {
        "title": "Rubén Alvarado | Software Developer & Comic Enthusiast",
        "description": "Personal portfolio of Rubén Alvarado: fullstack developer, creative writer, and comic book lover."
    },
    "HomePage": {
        "title": "Hi, I'm Rubén ✨",
        "description": "Fullstack developer, creative storyteller, and comic book fan. This site is a window into my work, my ideas, and my passion for storytelling.",
        "projects": "View Projects"
    },
    "Manifest":{
        "name": "Rubén Alvarado's Portfolio",
        "short_name": "Rubén's Portfolio",
        "description": "Personal portfolio of Rubén Alvarado: fullstack developer, creative writer, and comic book lover.",
        "start_url": "/",
        "display": "standalone",
        "theme_color": "#FBBF24",
        "background_color": "#FBBF24",
        "icons": [
            {
                "src": "/icon-192x192.png",
                "sizes": "192x192",
                "type": "image/png"
            },
            {
                "src": "/icon-512x512.png",
                "sizes": "512x512",
                "type": "image/png"
            }
        ]
    }
};
export default messages;